[package]
name = "skyrim-saves"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
rfd = "0.6.3"
tracing = "0.1.29"
tracing-subscriber = "0.3.3"
