name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger this workflow for tags like v1.0.0

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_release:
    runs-on: windows-latest  # Use a Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc  # Target for Windows

    - name: Build
      run: cargo rustc --release -- -Clink-args="/SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup"

    - name: Debug list files
      run: dir ./target/release/

    - name: Install ghr
      run: |
        Invoke-WebRequest -Uri "https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_windows_amd64.zip" -OutFile "ghr.zip"
        Expand-Archive -Path "ghr.zip" -DestinationPath "C:\ghr"

    - name: Debug list ghr directory
      run: dir C:\ghr

    - name: Create GitHub Release and Upload Asset using ghr
      run: |
        C:\ghr\ghr_v0.13.0_windows_amd64\ghr.exe -t ${{ secrets.GITHUB_TOKEN }} \
            -u ${{ github.repository_owner }} \
            -r ${{ github.event.repository.name }} \
            -c ${{ github.sha }} \
            -n "Release ${{ github.ref }}" \
            -b "Release notes for ${{ github.ref }}" \
            -replace \
            ${{ github.ref }} ./target/release/arcanaeum.exe
