name: Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_release:
    runs-on: windows-latest  # Use a Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc  # Target for Windows

    - name: Build
      run: cargo rustc --release -- -Clink-args="/SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup"
    
    - name: Debug list files
      run: dir ./target/release/

    - name: Upload to GitHub Releases
      if: startsWith(github.ref, 'refs/tags/')  # Only upload on tagged commits
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }} # Provided by GitHub
        asset_path: ./target/release/arcanaeum.exe  # Replace with your binary name
        asset_name: arcanaeum.exe  # Replace with your binary name
        asset_content_type: application/octet-stream
